hljs_theme:
  description: "Select the theme you want code blocks to use. You can visit <a target='_blank' href='https://highlightjs.org/static/demo/'>the hljs demo page</a> to preview the themes"
  default: github
  type: enum
  choices:
    - a11y-dark
    - a11y-light
    - agate
    - androidstudio
    - an-old-hope
    - arduino-light
    - arta
    - ascetic
    - atom-one-dark
    - atom-one-dark-reasonable
    - atom-one-light
    - brown-paper
    - codepen-embed
    - color-brewer
    - dark
    - default
    - devibeans
    - docco
    - far
    - felipec
    - foundation
    - github
    - github-dark
    - github-dark-dimmed
    - gml
    - googlecode
    - gradient-dark
    - gradient-light
    - grayscale
    - hybrid
    - idea
    - intellij-light
    - ir-black
    - isbl-editor-dark
    - isbl-editor-light
    - kimbie-dark
    - kimbie-light
    - lightfair
    - lioshi
    - magula
    - mono-blue
    - monokai
    - monokai-sublime
    - night-owl
    - nnfx-dark
    - nnfx-light
    - nord
    - obsidian
    - panda-syntax-dark
    - panda-syntax-light
    - paraiso-dark
    - paraiso-light
    - pojoaque
    - purebasic
    - qtcreator-dark
    - qtcreator-light
    - rainbow
    - routeros
    - school-book
    - shades-of-purple
    - srcery
    - stackoverflow-dark
    - stackoverflow-light
    - sunburst
    - tokyo-night-dark
    - tokyo-night-light
    - tomorrow-night-blue
    - tomorrow-night-bright
    - vs2015
    - vs
    - xcode
    - xt256
hljs_dark_match:
  default: false
  description: "Load dark color scheme if available"
