hljs_theme:
  description: "Select the theme you want code blocks to use. You can visit <a target='_blank' href='https://highlightjs.org/static/demo/'>the hljs demo page</a> to preview the themes"
  default: github
  type: enum
  choices:
    - a11y-dark
    - a11y-light
    - agate
    - androidstudio
    - an-old-hope
    - arduino-light
    - arta
    - ascetic
    - atelier-cave-dark
    - atelier-cave-light
    - atelier-dune-dark
    - atelier-dune-light
    - atelier-estuary-dark
    - atelier-estuary-light
    - atelier-forest-dark
    - atelier-forest-light
    - atelier-heath-dark
    - atelier-heath-light
    - atelier-lakeside-dark
    - atelier-lakeside-light
    - atelier-plateau-dark
    - atelier-plateau-light
    - atelier-savanna-dark
    - atelier-savanna-light
    - atelier-seaside-dark
    - atelier-seaside-light
    - atelier-sulphurpool-dark
    - atelier-sulphurpool-light
    - atom-one-dark-reasonable
    - atom-one-dark
    - atom-one-light
    - brown-paper
    - codepen-embed
    - color-brewer
    - darcula
    - dark
    - default
    - docco
    - dracula
    - far
    - foundation
    - github-gist
    - github-dark
    - github
    - gml
    - googlecode
    - gradient-dark
    - grayscale
    - gruvbox-dark
    - gruvbox-light
    - hopscotch
    - hybrid
    - idea
    - ir-black
    - isbl-editor-dark
    - isbl-editor-light
    - kimbie-dark
    - kimbie-light
    - lightfair
    - magula
    - mono-blue
    - monokai
    - monokai-sublime
    - night-owl
    - nord
    - obsidian
    - ocean
    - paraiso-dark
    - paraiso-light
    - pojoaque
    - purebasic
    - qtcreator_dark
    - qtcreator_light
    - railscasts
    - rainbow
    - routeros
    - school-book
    - shades-of-purple
    - solarized-dark
    - solarized-light
    - sunburst
    - tomorrow-night-blue
    - tomorrow-night-bright
    - tomorrow-night-eighties
    - tomorrow-night
    - tomorrow
    - vs2015
    - vs
    - xcode
    - xt256
    - zenburn
hljs_dark_match:
  default: false
  description: "Load dark color scheme if available"
